export enum QUEUE_NAME {
  IMAGE = 'IMAGE',
  EMAIL = 'EMAIL',
  FORGOT_PASSWORD_EMAIL = 'FORGOT_PASSWORD_EMAIL',
}

export enum QUEUE_TOPIC {
  EMAIL_SEND = 'EMAIL_SEND',
  IMAGE_RESIZE = 'IMAGE_RESIZE',
  FORGOT_PASSWORD_EMAIL_SEND = 'FORGOT_PASSWORD_EMAIL_SEND',
}
